# Generated by Django 2.1.8 on 2019-09-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(blank=True, max_length=32, null=True)),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('phone_num', models.CharField(blank=True, max_length=32, null=True)),
                ('address', models.TextField()),
                ('photo', models.ImageField(upload_to='image')),
            ],
        ),
    ]
