# Generated by Django 2.1.8 on 2019-09-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.CharField(max_length=11)),
                ('goods_name', models.CharField(max_length=128)),
                ('goods_price', models.FloatField()),
                ('goods_count', models.IntegerField()),
                ('goods_location', models.CharField(max_length=254)),
                ('goods_pro_date', models.DateField(auto_now=True)),
                ('goods_save_month', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='loginuser',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='phone_num',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
