# Generated by Django 2.1.8 on 2019-09-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='phone_num',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
