# Generated by Django 2.1.8 on 2019-09-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0003_goods_goods_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='age',
            field=models.IntegerField(default=23),
        ),
    ]
