# Generated by Django 2.1.8 on 2019-09-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payorder',
            name='goods_number',
            field=models.IntegerField(default=1),
        ),
    ]
