# Generated by Django 2.1.8 on 2019-08-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.FileField(max_length=64, upload_to='app/static/app/upload', verbose_name='图片地址')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('summary', models.CharField(max_length=128, verbose_name='简介')),
            ],
            options={
                'verbose_name_plural': '图片',
            },
        ),
    ]
