# Generated by Django 2.1.8 on 2019-09-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_loginuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=32)),
                ('type_desc', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='photo',
            field=models.ImageField(upload_to='seller/images'),
        ),
    ]
