# Generated by Django 2.1.8 on 2019-09-09 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_auto_20190909_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_picture',
            field=models.ImageField(default='seller/images/abc.jpeg', upload_to='seller/images'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Seller.LoginUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Seller.GoodsType'),
            preserve_default=False,
        ),
    ]
