# Generated by Django 2.1.8 on 2019-09-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0005_auto_20190909_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_picture',
            field=models.ImageField(default='seller/images/abc.jpg', upload_to='seller/images'),
        ),
    ]
